[package]
name = "terge"
version = "0.1.0"
edition = "2024"

[[example]]
name = "counter"
path = "examples/counter.rs"

[[example]]
name = "pong"
path = "examples/pong.rs"

[dependencies]
crossterm = "0.29"
log = "0.4"

[dev-dependencies]
pretty_env_logger = "0.4"
